In [9]:
import numpy as np
a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3],# a matrix
              [4,5,6,7]])
d = np.zeros((2,4))#(2x4 matrix of zeros) 
e = np.random.rand(2,5) # random 2x5

vec1 = np.zeros((1,4)) # vector of length 4
vec2 = np.zeros((4,3)) # matrix with 4 rows & 3 columns
resultVec = vec1.dot(vec2)

# matrix with all numbers between 0 and 1
print(a)
print (b)
print (c)
print (d)
print(e)
print (resultVec.shape)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.64604081  0.40688636  0.16397301  0.46849684  0.1868847 ]
 [ 0.19482759  0.12193496  0.64987193  0.08485883  0.35487768]]
(1, 3)
